enum Strings {
  //Page Login
  emailInputHint,
  passwordInputHint,
  buttonTextLogin,
  msgErrorDataEmpty,
  msgErrorUser,
  msgErrorPassword,
  //Page User
  titlePageUser,
  buttonClients,
  buttonSure,
  buttonSinester,
  buttonAdmin,
  msgErrorAdmin,
  //Page Client
  titlePageClient,
  textAddClient,
  titlePageClientFormAdd,
  titlePageClientFormEdit,
  lastName1HintInput,
  lastName2HintInput,
  //Page Settings
  settingsPageTitle,
  settingsThemeOptionTitle,
  settingsLanguajeOptionTitle,
  languajeOptionSpanish,
  languajeOptionEnglish,
  //General
  textPhone,
  textPhoneComplete,
  textCity,
  textPostalCard,
  textPostalDetail,
  textDetailViaTitle,
  textClass,
  textName,
  textNumber,
  textObservation,
  textAddColumn,
  msgNoInternet,
  msgErrorSave,
  msgErrorupdate,
  msgErrorDelete,
  classViaHintInput,
  nameViaHintInput,
  numberViaHintInput,
  buttonRegister,
  buttonUpdate,
  msgErrorFormValidation,
  dataTypeHint,
  titlePageAddField,
  buttonAddField,
  //Delete Dialog
  deleteDialogMsg,
  deleteDialogTitle,
  deleteDialogCancel,
  deleteDialogDelete,
  deleteDialogMsgDelete,
  //Page Sure
  titlePageSure,
  textAddSure,
  titlePageSureFormAdd,
  titlePageSureFormEdit,
  textDniClient,
  textPoliza,
  textRamo,
  textVigencia,
  textInicio,
  textFin,
  textFechaInicio,
  textFechaFin,
  polizaHintText,
  condiconesHintText,
}