import 'package:login_bloc/utils/app_string.dart';

const Map<Strings, String> dictionary_es = {
  //Page Login
  Strings.emailInputHint: "Correo",
  Strings.passwordInputHint: "Contraseña",
  Strings.buttonTextLogin: "Ingresar",
  Strings.msgErrorDataEmpty: "Por favor introduzca todos los datos",
  Strings.msgErrorUser: "Este usuario no existe",
  Strings.msgErrorPassword: "Contraseña incorrecta",
  //Page User
  Strings.titlePageUser: "Mi Perfil",
  Strings.buttonClients: "Ver clientes",
  Strings.buttonSure: "Ver seguros",
  Strings.buttonSinester: "Ver siniestros",
  Strings.buttonAdmin: "Ser admin",
  Strings.msgErrorAdmin: "No está autorizado para realizar esta operación",
  //Page Client
  Strings.titlePageClient: "Clientes",
  Strings.textAddClient: "Agregar cliente",
  Strings.titlePageClientFormAdd: "Nuevo cliente",
  Strings.titlePageClientFormEdit: "Editar cliente",
  Strings.lastName1HintInput: "Primer apellido",
  Strings.lastName2HintInput: "Segundo apellido",
  //Page Settings
  Strings.settingsPageTitle: "Ajustes",
  Strings.settingsThemeOptionTitle: "Tema",
  Strings.settingsLanguajeOptionTitle: "Idioma",
  Strings.languajeOptionSpanish: "Español",
  Strings.languajeOptionEnglish: "Ingles",
  //General
  Strings.textPhone: "Tel",
  Strings.textPhoneComplete : "Teléfono",
  Strings.textCity: "Ciudad",
  Strings.textPostalCard: "Cod. Postal",
  Strings.textPostalDetail: "Cod.P",
  Strings.textDetailViaTitle: "Detalle de Vía",
  Strings.textClass: "Clase",
  Strings.textName: "Nombre",
  Strings.textNumber: "Número",
  Strings.textObservation: "Observaciones",
  Strings.textAddColumn: "Agregar columna",
  Strings.msgNoInternet: "No puede realizar la operación sin internet",
  Strings.msgErrorSave: "No se guardó debido a un error",
  Strings.msgErrorupdate: "Error, no se pudo actualizar",
  Strings.msgErrorDelete: "Error al intentar eliminar",
  Strings.classViaHintInput: "Clase vía",
  Strings.nameViaHintInput: "Nombre vía",
  Strings.numberViaHintInput: "Número vía",
  Strings.buttonRegister: "Registrar",
  Strings.buttonUpdate: "Actualizar",
  Strings.msgErrorFormValidation: "Error, debe llenar los campos obligatorios",
  Strings.dataTypeHint: "Tipo de dato",
  Strings.titlePageAddField: "Añadir columna",
  Strings.buttonAddField: "Agregar",
  //Delete Dialog
  Strings.deleteDialogMsg: "¿Está seguro? no podrás deshacer esta acción",
  Strings.deleteDialogTitle: "Eliminar",
  Strings.deleteDialogCancel: "Cancelar",
  Strings.deleteDialogDelete: "Eliminar",
  Strings.deleteDialogMsgDelete: "Dato eliminado"
};
