import 'package:login_bloc/utils/app_string.dart';

const Map<Strings, String> dictionary_en = {
  //Page Login
  Strings.emailInputHint: "Email",
  Strings.passwordInputHint: "Password",
  Strings.buttonTextLogin: "Log In",
  Strings.msgErrorDataEmpty: "Please enter all the data",
  Strings.msgErrorUser: "This user does not exist",
  Strings.msgErrorPassword: "Incorrect password",
  //Page User
  Strings.titlePageUser: "Profile",
  Strings.buttonClients: "See clients",
  Strings.buttonSure: "See insurance",
  Strings.buttonSinester: "See claims",
  Strings.buttonAdmin: "be admin",
  Strings.msgErrorAdmin: "You are not authorized to perform this operation",
  //Page Client
  Strings.titlePageClient: "Clients",
  Strings.textAddClient: "Add client",
  Strings.titlePageClientFormAdd: "New client",
  Strings.titlePageClientFormEdit: "Edit client",
  Strings.lastName1HintInput: "Surname",
  Strings.lastName2HintInput: "Second surname",
  //Page Settings
  Strings.settingsPageTitle: "Settings",
  Strings.settingsThemeOptionTitle: "Theme",
  Strings.settingsLanguajeOptionTitle: "Languaje",
  Strings.languajeOptionSpanish: "Spanish",
  Strings.languajeOptionEnglish: "English",
  //General
  Strings.textPhone: "Phone",
  Strings.textPhoneComplete : "Phone",
  Strings.textCity: "City",
  Strings.textPostalCard: "Postal C.",
  Strings.textPostalDetail: "P.C",
  Strings.textDetailViaTitle: "Track Detail",
  Strings.textClass: "Class",
  Strings.textName: "Name",
  Strings.textNumber: "Number",
  Strings.textObservation: "Observations",
  Strings.textAddColumn: "Add column",
  Strings.msgNoInternet: "You cannot perform the operation without internet",
  Strings.msgErrorSave: "It was not saved due to an error",
  Strings.msgErrorupdate: "Error, could not update",
  Strings.msgErrorDelete: "Error trying to delete",
  Strings.classViaHintInput: "Track class",
  Strings.nameViaHintInput: "Track name",
  Strings.numberViaHintInput: "Track number",
  Strings.buttonRegister: "To register",
  Strings.buttonUpdate: "To update",
  Strings.msgErrorFormValidation: "Error, you must fill in the required fields",
  Strings.dataTypeHint: "Data type",
  Strings.titlePageAddField: "Add field",
  Strings.buttonAddField: "Add",
  //Delete Dialog
  Strings.deleteDialogMsg: "Are you sure? you will not be able to undo this action",
  Strings.deleteDialogTitle: "Delete",
  Strings.deleteDialogCancel: "Cancel",
  Strings.deleteDialogDelete: "Remove",
  Strings.deleteDialogMsgDelete: "Deleted data"
};
