import 'package:login_bloc/utils/app_string.dart';

const Map<Strings, String> dictionary_es = {
  //Page Login
  Strings.emailInputHint: "Correo",
  Strings.passwordInputHint: "Contraseña",
  Strings.buttonTextLogin: "Ingresar",
  Strings.msgErrorDataEmpty: "Por favor introduzca todos los datos",
  Strings.msgErrorUser: "Este usuario no existe",
  Strings.msgErrorPassword: "Contraseña incorrecta",
  //Page User
  Strings.titlePageUser: "Mi Perfil",
  Strings.buttonClients: "Ver clientes",
  Strings.buttonSure: "Ver seguros",
  Strings.buttonSinester: "Ver siniestros",
  Strings.buttonAdmin: "Ser admin",
  Strings.msgErrorAdmin: "No está autorizado para realizar esta operación",
  //Page Client
  Strings.titlePageClient: "Clientes",
  Strings.textAddClient: "Agregar cliente",
  Strings.titlePageClientFormAdd: "Nuevo cliente",
  Strings.titlePageClientFormEdit: "Editar cliente",
  Strings.lastName1HintInput: "Primer apellido",
  Strings.lastName2HintInput: "Segundo apellido",
  //Page Settings
  Strings.settingsPageTitle: "Ajustes",
  Strings.settingsThemeOptionTitle: "Tema",
  Strings.settingsLanguajeOptionTitle: "Idioma",
  Strings.languajeOptionSpanish: "Español",
  Strings.languajeOptionEnglish: "Ingles",
  //General
  Strings.textPhone: "Tel",
  Strings.textPhoneComplete : "Teléfono",
  Strings.textCity: "Ciudad",
  Strings.textPostalCard: "Cod. Postal",
  Strings.textPostalDetail: "Cod.P",
  Strings.textDetailViaTitle: "Detalle de Vía",
  Strings.textClass: "Clase",
  Strings.textName: "Nombre",
  Strings.textNumber: "Número",
  Strings.textObservation: "Observaciones",
  Strings.textAddColumn: "Agregar columna",
  Strings.msgNoInternet: "No puede realizar la operación sin internet",
  Strings.msgErrorSave: "No se guardó debido a un error",
  Strings.msgErrorupdate: "Error, no se pudo actualizar",
  Strings.msgErrorDelete: "Error al intentar eliminar",
  Strings.classViaHintInput: "Clase vía",
  Strings.nameViaHintInput: "Nombre vía",
  Strings.numberViaHintInput: "Número vía",
  Strings.buttonRegister: "Registrar",
  Strings.buttonUpdate: "Actualizar",
  Strings.msgErrorFormValidation: "Error, debe llenar los campos obligatorios",
  Strings.dataTypeHint: "Tipo de dato",
  Strings.titlePageAddField: "Añadir columna",
  Strings.buttonAddField: "Agregar",
  //Delete Dialog
  Strings.deleteDialogMsg: "¿Está seguro? no podrás deshacer esta acción",
  Strings.deleteDialogTitle: "Eliminar",
  Strings.deleteDialogCancel: "Cancelar",
  Strings.deleteDialogDelete: "Eliminar",
  Strings.deleteDialogMsgDelete: "Dato eliminado",
  //Page Sure
  Strings.titlePageSure: "Seguro",
  Strings.textAddSure: "Agregar seguro",
  Strings.titlePageSureFormAdd: "Nuevo seguro",
  Strings.titlePageSureFormEdit: "Editar seguro",
  Strings.textDniClient: "DNI Cliente",
  Strings.textPoliza: "Poliza",
  Strings.textRamo: "Ramo",
  Strings.textVigencia: "Vigencia",
  Strings.textInicio: "Inicio",
  Strings.textFin: "Fin",
  Strings.textFechaInicio: "Fecha Inicio",
  Strings.textFechaFin: "Fecha Fin",
  Strings.polizaHintText: "Num. Poliza",
  Strings.condiconesHintText: "Condición particular",
  //Page Siniestro
  Strings.titlePageClaim: "Siniestros",
  Strings.textAddClaim: "Agregar siniestro",
  Strings.titlePageClaimFormAdd: "Nuevo siniestro",
  Strings.titlePageClaimFormEdit: "Editar siniestro",
  Strings.textRechazado: "Rechazado",
  Strings.textAceptado: "Aceptado",
  Strings.textFecha: "Fecha",
  Strings.textIndemnizacion: "Indemnización",
  Strings.textEstado: "Estado",
  Strings.textCausas: "Causas",
  Strings.textIdSiniestro: "ID Siniestro",
  //Biometric
  Strings.msgBiometric: "Autentifíquese para autocompletar la contraseña",
  Strings.msgBiometricNotAvailable: "El dispositivo no tiene soporte de hardware para biometría",
  Strings.msgBiometricPasscodeNotSet: "Aún no ha configurado un código de acceso o PIN/patrón/contraseña en el dispositivo",
  Strings.msgBiometricNotEnrolled: "No ha inscrito ninguna biometría en el dispositivo",
  Strings.msgBiometricLockedOut: "El lector está bloqueada temporalmente debido a demasiados intentos",
  Strings.msgBiometricOtherOperatingSystem: "El sistema operativo del dispositivo no es compatible",
  Strings.msgBiometricPermanentlyLockedOut: "Se requiere una autenticación fuerte como PIN/Patrón/Contraseña para desbloquear",
  Strings.msgBiometricNoAutorized: "No tiene autorización de acceso"
};
