name: test login bloc
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: cd login_bloc 
    - run: flutter pub get
    - run: flutter test

